(() => { 'use strict';
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const loader = $('#loader'), film = $('.film'), phone = $('#phone'), states = $$('.screen-state');
  const head = $('#headline'), desc = $('#description'), feature = $('#feature'), sound = $('#soundToggle');
  const scenes = [
    ['One player.<br><em>Every sound.</em>', 'Music, discovery and sound engineering in one focused experience.', 'Ultra-premium<br>playback.', 'Queue, lyrics and controls designed to disappear behind the song.', [-3,-18,2]],
    ['Feel music.<br><em>In full.</em>', 'A specialized sound engine that makes space for the details.', 'Cicada<br>Immersive.', 'Signature EQ profiles from Dolby to Sennheiser, Sony and JBL.', [-4,24,-2]],
    ['One search.<br><em>Everywhere.</em>', 'Find the song you want without choosing a streaming world first.', 'Global<br>search.', 'Answers from Spotify and YouTube Music, together in one result.', [4,-31,3]],
    ['Your music.<br><em>One home.</em>', 'A single feed for favourites, new releases and everything you follow.', 'One beautiful<br>music home.', 'A personal feed that brings your music worlds together.', [-5,18,-3]]
  ];
  let current = -1, audio = null, master = null, scoreTimer = null;
  function scene() { const r = film.getBoundingClientRect(), p = Math.max(0, Math.min(.999, -r.top / Math.max(r.height - innerHeight, 1))), i = Math.min(3, Math.floor(p * 4)); const local = p * 4 - i, s = scenes[i]; if (i !== current) { current = i; states.forEach((x,n)=>x.classList.toggle('active',n===i)); feature.style.opacity=0; setTimeout(()=>{ feature.querySelector('.count').textContent=String(i+1).padStart(2,'0')+' / 04'; feature.querySelector('h2').innerHTML=s[2]; feature.querySelector('p:last-child').textContent=s[3]; head.innerHTML=s[0]; desc.textContent=s[1]; feature.style.opacity=1; },160); } phone.style.transform=`rotateX(${s[4][0]+local*1.5}deg) rotateY(${s[4][1]+local*7}deg) rotateZ(${s[4][2]}deg)`; }
  function drawCavern(){ const c=$('#cavern'), x=c.getContext('2d'); let t=0; function frame(){c.width=innerWidth;c.height=innerHeight; const g=x.createRadialGradient(c.width*.5,c.height*.43,0,c.width*.5,c.height*.43,Math.max(c.width,c.height)*.64);g.addColorStop(0,'#ffffff12');g.addColorStop(.38,'#3a243011');g.addColorStop(1,'#0000');x.clearRect(0,0,c.width,c.height);x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.strokeStyle='#ffffff12';for(let i=0;i<16;i++){let px=(i*197+t*.08)%c.width,py=c.height*.63+Math.sin(t*.001+i)*80;x.beginPath();x.moveTo(px,py);x.lineTo(px-50,py+250);x.stroke()}t++;requestAnimationFrame(frame)}frame()}
  function startSound(){ if(audio)return; audio=new AudioContext(); master=audio.createGain(); master.gain.value=.045; master.connect(audio.destination); const note=(hz,at,du,type='sine')=>{let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(hz,at);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.22,at+.7);g.gain.exponentialRampToValueAtTime(.0001,at+du);o.connect(g).connect(master);o.start(at);o.stop(at+du+.1)}; let n=0; scoreTimer=setInterval(()=>{let now=audio.currentTime;[65.41,77.78,98,116.54].forEach((h,i)=>note(h*(i===n%4?1:0.5),now+i*.08,3.2,'triangle'));note([130.81,146.83,155.56,174.61][n++%4],now+.4,2.7,'sine')},2900); }
  sound.addEventListener('click',()=>{let on=sound.getAttribute('aria-pressed')==='true';if(on){master.gain.setTargetAtTime(.0001,audio.currentTime,.2);sound.setAttribute('aria-pressed','false');sound.querySelector('span').textContent='Sound off'}else{startSound();audio.resume();master.gain.setTargetAtTime(.045,audio.currentTime,.2);sound.setAttribute('aria-pressed','true');sound.querySelector('span').textContent='Sound on'}});
  addEventListener('scroll',scene,{passive:true});addEventListener('resize',scene,{passive:true});scene();drawCavern();setTimeout(()=>loader.classList.add('done'),850);
})();
